#!/bin/bash

./mcpat -infile  ./xmlS/specbzip.xml -print_level 5 > specbzip.txt
./mcpat -infile  ./xmlS/specbzipB.xml -print_level 5 > specbzipB.txt
./mcpat -infile  ./xmlS/specbzipassoc1.xml -print_level 5 > specbzipassoc1.txt
./mcpat -infile  ./xmlS/specbzipassoc2.xml -print_level 5 > specbzipassoc2.txt
./mcpat -infile  ./xmlS/specbzipassoc4.xml -print_level 5 > specbzipassoc4.txt
./mcpat -infile  ./xmlS/specbzipassoc8.xml -print_level 5 > specbzipassoc8.txt
./mcpat -infile  ./xmlS/specbzipassoc16.xml -print_level 5 > specbzipassoc16.txt
./mcpat -infile  ./xmlS/specbzipCLine16.xml -print_level 5 > specbzipCLine16.txt
./mcpat -infile  ./xmlS/specbzipCLine32.xml -print_level 5 > specbzipCLine32.txt
./mcpat -infile  ./xmlS/specbzipCLine64.xml -print_level 5 > specbzipCLine64.txt
./mcpat -infile  ./xmlS/specbzipCLine128.xml -print_level 5 > specbzipCLine128.txt
./mcpat -infile  ./xmlS/specbzipCLine256.xml -print_level 5 > specbzipCLine256.txt
./mcpat -infile  ./xmlS/specbzip16_32.xml -print_level 5 >  specbzip16_32.txt
./mcpat -infile  ./xmlS/specbzip32_64.xml -print_level 5 > specbzip32_64.txt
./mcpat -infile  ./xmlS/specbzip64_128.xml -print_level 5 > specbzip64_128.txt
./mcpat -infile  ./xmlS/specbzip128_256.xml -print_level 5 > specbzip128_256.txt
./mcpat -infile  ./xmlS/specbzip256.xml -print_level 5 > specbzip256.txt
./mcpat -infile  ./xmlS/specbzip512.xml -print_level 5 > specbzip512.txt
./mcpat -infile  ./xmlS/specbzip1024.xml -print_level 5 > specbzip1024.txt
./mcpat -infile  ./xmlS/specbzip2048.xml -print_level 5 > specbzip2048.txt
./mcpat -infile  ./xmlS/specbzip4096.xml -print_level 5 > specbzip4096.txt
./mcpat -infile  ./xmlS/specbzip32_64_512.xml -print_level 5 > specbzip32_64_512.txt
./mcpat -infile  ./xmlS/specbzip64_128_1024.xml -print_level 5 > specbzip64_128_1024.txt
./mcpat -infile  ./xmlS/specbzip128_256_2048.xml -print_level 5 > specbzip128_256_2048.txt

./mcpat -infile  ./xmlS/spechmmer.xml -print_level 5 > spechmmer.txt
./mcpat -infile  ./xmlS/spechmmerB.xml -print_level 5 > spechmmerB.txt
./mcpat -infile  ./xmlS/spechmmerassoc1.xml -print_level 5 > spechmmerassoc1.txt
./mcpat -infile  ./xmlS/spechmmerassoc2.xml -print_level 5 > spechmmerassoc2.txt
./mcpat -infile  ./xmlS/spechmmerassoc4.xml -print_level 5 > spechmmerassoc4.txt
./mcpat -infile  ./xmlS/spechmmerassoc8.xml -print_level 5 > spechmmerassoc8.txt
./mcpat -infile  ./xmlS/spechmmerassoc16.xml -print_level 5 > spechmmerassoc16.txt
./mcpat -infile  ./xmlS/spechmmerCLine16.xml -print_level 5 > spechmmerCLine16.txt
./mcpat -infile  ./xmlS/spechmmerCLine32.xml -print_level 5 > spechmmerCLine32.txt
./mcpat -infile  ./xmlS/spechmmerCLine64.xml -print_level 5 > spechmmerCLine64.txt
./mcpat -infile  ./xmlS/spechmmerCLine128.xml -print_level 5 > spechmmerCLine128.txt
./mcpat -infile  ./xmlS/spechmmerCLine256.xml -print_level 5 > spechmmerCLine256.txt
./mcpat -infile  ./xmlS/spechmmer16_32.xml -print_level 5 >  spechmmer16_32.txt
./mcpat -infile  ./xmlS/spechmmer32_64.xml -print_level 5 > spechmmer32_64.txt
./mcpat -infile  ./xmlS/spechmmer64_128.xml -print_level 5 > spechmmer64_128.txt
./mcpat -infile  ./xmlS/spechmmer128_256.xml -print_level 5 > spechmmer128_256.txt
./mcpat -infile  ./xmlS/spechmmer256.xml -print_level 5 > spechmmer256.txt
./mcpat -infile  ./xmlS/spechmmer512.xml -print_level 5 > spechmmer512.txt
./mcpat -infile  ./xmlS/spechmmer1024.xml -print_level 5 > spechmmer1024.txt
./mcpat -infile  ./xmlS/spechmmer2048.xml -print_level 5 > spechmmer2048.txt
./mcpat -infile  ./xmlS/spechmmer4096.xml -print_level 5 > spechmmer4096.txt
./mcpat -infile  ./xmlS/spechmmer32_64_512.xml -print_level 5 > spechmmer32_64_512.txt
./mcpat -infile  ./xmlS/spechmmer64_128_1024.xml -print_level 5 > spechmmer64_128_1024.txt
./mcpat -infile  ./xmlS/spechmmer128_256_2048.xml -print_level 5 > spechmmer128_256_2048.txt

./mcpat -infile  ./xmlS/speclibm.xml -print_level 5 > speclibm.txt
./mcpat -infile  ./xmlS/speclibmB.xml -print_level 5 > speclibmB.txt
./mcpat -infile  ./xmlS/speclibmassoc1.xml -print_level 5 > speclibmassoc1.txt
./mcpat -infile  ./xmlS/speclibmassoc2.xml -print_level 5 > speclibmassoc2.txt
./mcpat -infile  ./xmlS/speclibmassoc4.xml -print_level 5 > speclibmassoc4.txt
./mcpat -infile  ./xmlS/speclibmassoc8.xml -print_level 5 > speclibmassoc8.txt
./mcpat -infile  ./xmlS/speclibmassoc16.xml -print_level 5 > speclibmassoc16.txt
./mcpat -infile  ./xmlS/speclibmCLine16.xml -print_level 5 > speclibmCLine16.txt
./mcpat -infile  ./xmlS/speclibmCLine32.xml -print_level 5 > speclibmCLine32.txt
./mcpat -infile  ./xmlS/speclibmCLine64.xml -print_level 5 > speclibmCLine64.txt
./mcpat -infile  ./xmlS/speclibmCLine128.xml -print_level 5 > speclibmCLine128.txt
./mcpat -infile  ./xmlS/speclibmCLine256.xml -print_level 5 > speclibmCLine256.txt
./mcpat -infile  ./xmlS/speclibm16_32.xml -print_level 5 >  speclibm16_32.txt
./mcpat -infile  ./xmlS/speclibm32_64.xml -print_level 5 > speclibm32_64.txt
./mcpat -infile  ./xmlS/speclibm64_128.xml -print_level 5 > speclibm64_128.txt
./mcpat -infile  ./xmlS/speclibm128_256.xml -print_level 5 > speclibm128_256.txt
./mcpat -infile  ./xmlS/speclibm256.xml -print_level 5 > speclibm256.txt
./mcpat -infile  ./xmlS/speclibm512.xml -print_level 5 > speclibm512.txt
./mcpat -infile  ./xmlS/speclibm1024.xml -print_level 5 > speclibm1024.txt
./mcpat -infile  ./xmlS/speclibm2048.xml -print_level 5 > speclibm2048.txt
./mcpat -infile  ./xmlS/speclibm4096.xml -print_level 5 > speclibm4096.txt
./mcpat -infile  ./xmlS/speclibm32_64_512.xml -print_level 5 > speclibm32_64_512.txt
./mcpat -infile  ./xmlS/speclibm64_128_1024.xml -print_level 5 > speclibm64_128_1024.txt
./mcpat -infile  ./xmlS/speclibm128_256_2048.xml -print_level 5 > speclibm128_256_2048.txt


./mcpat -infile  ./xmlS/specmcf.xml -print_level 5 > specmcf.txt
./mcpat -infile  ./xmlS/specmcfB.xml -print_level 5 > specmcfB.txt
./mcpat -infile  ./xmlS/specmcfassoc1.xml -print_level 5 > specmcfassoc1.txt
./mcpat -infile  ./xmlS/specmcfassoc2.xml -print_level 5 > specmcfassoc2.txt
./mcpat -infile  ./xmlS/specmcfassoc4.xml -print_level 5 > specmcfassoc4.txt
./mcpat -infile  ./xmlS/specmcfassoc8.xml -print_level 5 > specmcfassoc8.txt
./mcpat -infile  ./xmlS/specmcfassoc16.xml -print_level 5 > specmcfassoc16.txt
./mcpat -infile  ./xmlS/specmcfCLine16.xml -print_level 5 > specmcfCLine16.txt
./mcpat -infile  ./xmlS/specmcfCLine32.xml -print_level 5 > specmcfCLine32.txt
./mcpat -infile  ./xmlS/specmcfCLine64.xml -print_level 5 > specmcfCLine64.txt
./mcpat -infile  ./xmlS/specmcfCLine128.xml -print_level 5 > specmcfCLine128.txt
./mcpat -infile  ./xmlS/specmcfCLine256.xml -print_level 5 > specmcfCLine256.txt
./mcpat -infile  ./xmlS/specmcf16_32.xml -print_level 5 >  specmcf16_32.txt
./mcpat -infile  ./xmlS/specmcf32_64.xml -print_level 5 > specmcf32_64.txt
./mcpat -infile  ./xmlS/specmcf64_128.xml -print_level 5 > specmcf64_128.txt
./mcpat -infile  ./xmlS/specmcf128_256.xml -print_level 5 > specmcf128_256.txt
./mcpat -infile  ./xmlS/specmcf256.xml -print_level 5 > specmcf256.txt
./mcpat -infile  ./xmlS/specmcf512.xml -print_level 5 > specmcf512.txt
./mcpat -infile  ./xmlS/specmcf1024.xml -print_level 5 > specmcf1024.txt
./mcpat -infile  ./xmlS/specmcf2048.xml -print_level 5 > specmcf2048.txt
./mcpat -infile  ./xmlS/specmcf4096.xml -print_level 5 > specmcf4096.txt
./mcpat -infile  ./xmlS/specmcf32_64_512.xml -print_level 5 > specmcf32_64_512.txt
./mcpat -infile  ./xmlS/specmcf64_128_1024.xml -print_level 5 > specmcf64_128_1024.txt
./mcpat -infile  ./xmlS/specmcf128_256_2048.xml -print_level 5 > specmcf128_256_2048.txt

./mcpat -infile  ./xmlS/specsjeng.xml -print_level 5 > specsjeng.txt
./mcpat -infile  ./xmlS/specsjengB.xml -print_level 5 > specsjengB.txt
./mcpat -infile  ./xmlS/specsjengassoc1.xml -print_level 5 > specsjengassoc1.txt
./mcpat -infile  ./xmlS/specsjengassoc2.xml -print_level 5 > specsjengassoc2.txt
./mcpat -infile  ./xmlS/specsjengassoc4.xml -print_level 5 > specsjengassoc4.txt
./mcpat -infile  ./xmlS/specsjengassoc8.xml -print_level 5 > specsjengassoc8.txt
./mcpat -infile  ./xmlS/specsjengassoc16.xml -print_level 5 > specsjengassoc16.txt
./mcpat -infile  ./xmlS/specsjengCLine16.xml -print_level 5 > specsjengCLine16.txt
./mcpat -infile  ./xmlS/specsjengCLine32.xml -print_level 5 > specsjengCLine32.txt
./mcpat -infile  ./xmlS/specsjengCLine64.xml -print_level 5 > specsjengCLine64.txt
./mcpat -infile  ./xmlS/specsjengCLine128.xml -print_level 5 > specsjengCLine128.txt
./mcpat -infile  ./xmlS/specsjengCLine256.xml -print_level 5 > specsjengCLine256.txt
./mcpat -infile  ./xmlS/specsjeng16_32.xml -print_level 5 >  specsjeng16_32.txt
./mcpat -infile  ./xmlS/specsjeng32_64.xml -print_level 5 > specsjeng32_64.txt
./mcpat -infile  ./xmlS/specsjeng64_128.xml -print_level 5 > specsjeng64_128.txt
./mcpat -infile  ./xmlS/specsjeng128_256.xml -print_level 5 > specsjeng128_256.txt
./mcpat -infile  ./xmlS/specsjeng256.xml -print_level 5 > specsjeng256.txt
./mcpat -infile  ./xmlS/specsjeng512.xml -print_level 5 > specsjeng512.txt
./mcpat -infile  ./xmlS/specsjeng1024.xml -print_level 5 > specsjeng1024.txt
./mcpat -infile  ./xmlS/specsjeng2048.xml -print_level 5 > specsjeng2048.txt
./mcpat -infile  ./xmlS/specsjeng4096.xml -print_level 5 > specsjeng4096.txt
./mcpat -infile  ./xmlS/specsjeng32_64_512.xml -print_level 5 > specsjeng32_64_512.txt
./mcpat -infile  ./xmlS/specsjeng64_128_1024.xml -print_level 5 > specsjeng64_128_1024.txt
./mcpat -infile  ./xmlS/specsjeng128_256_2048.xml -print_level 5 > specsjeng128_256_2048.txt
