#!/bin/bash

python ./Scripts/print_energy.py specbzip.txt  ./spec_results/specbzip/stats.txt 
python ./Scripts/print_energy.py specbzipB.txt ./spec_results/specbzipB/stats.txt 
python ./Scripts/print_energy.py specbzipassoc1.txt  ./spec_results/specbzipassoc1/stats.txt 
python ./Scripts/print_energy.py specbzipassoc2.txt  ./spec_results/specbzipassoc2/stats.txt 
python ./Scripts/print_energy.py specbzipassoc4.txt  ./spec_results/specbzipassoc4/stats.txt 
python ./Scripts/print_energy.py specbzipassoc8.txt  ./spec_results/specbzipassoc8/stats.txt 
python ./Scripts/print_energy.py specbzipassoc16.txt  ./spec_results/specbzipassoc16/stats.txt 
python ./Scripts/print_energy.py specbzipCLine16.txt  ./spec_results/specbzipCLine16/stats.txt 
python ./Scripts/print_energy.py specbzipCLine32.txt  ./spec_results/specbzipCLine32/stats.txt 
python ./Scripts/print_energy.py specbzipCLine64.txt  ./spec_results/specbzipCLine64/stats.txt 
python ./Scripts/print_energy.py specbzipCLine128.txt ./spec_results/specbzipCLine128/stats.txt 
python ./Scripts/print_energy.py specbzipCLine256.txt ./spec_results/specbzipCLine256/stats.txt   
python ./Scripts/print_energy.py specbzip16_32.txt ./spec_results/specbzip16_32/stats.txt  
python ./Scripts/print_energy.py specbzip32_64.txt ./spec_results/specbzip32_64/stats.txt  
python ./Scripts/print_energy.py specbzip64_128.txt ./spec_results/specbzip64_128/stats.txt 
python ./Scripts/print_energy.py specbzip.128_256.txt ./spec_results/specbzip128_256/stats.txt 
python ./Scripts/print_energy.py specbzip256.txt ./spec_results/specbzip256/stats.txt 
python ./Scripts/print_energy.py specbzip512.txt ./spec_results/specbzip512/stats.txt 
python ./Scripts/print_energy.py specbzip1024.txt ./spec_results/specbzip1024/stats.txt  
python ./Scripts/print_energy.py specbzip2048.txt ./spec_results/specbzip2048/stats.txt  
python ./Scripts/print_energy.py specbzip4096.txt ./spec_results/specbzip4096/stats.txt 
python ./Scripts/print_energy.py specbzip32_64_512.txt ./spec_results/specbzip32_64_512/stats.txt 
python ./Scripts/print_energy.py specbzip64_128_1024.txt ./spec_results/specbzip64_128_1024/stats.txt 
python ./Scripts/print_energy.py specbzip128_256_2048.txt ./spec_results/specbzip128_256_2048/stats.txt  

python ./Scripts/print_energy.py spechmmer.txt ./spec_results/spechmmer/stats.txt 
python ./Scripts/print_energy.py spechmmerB.txt  ./spec_results/spechmmerB/stats.txt 
python ./Scripts/print_energy.py spechmmerassoc1.txt ./spec_results/spechmmerassoc1/stats.txt 
python ./Scripts/print_energy.py spechmmerassoc2.txt ./spec_results/spechmmerassoc2/stats.txt 
python ./Scripts/print_energy.py spechmmerassoc4.txt ./spec_results/spechmmerassoc4/stats.txt 
python ./Scripts/print_energy.py spechmmerassoc8.txt ./spec_results/spechmmerassoc8/stats.txt 
python ./Scripts/print_energy.py spechmmerassoc16.txt ./spec_results/spechmmerassoc16/stats.txt  
python ./Scripts/print_energy.py spechmmerCLine16.txt ./spec_results/spechmmerCLine16/stats.txt  
python ./Scripts/print_energy.py spechmmerCLine32.txt ./spec_results/spechmmerCLine32/stats.txt  
python ./Scripts/print_energy.py spechmmerCLine64.txt ./spec_results/spechmmerCLine64/stats.txt 
python ./Scripts/print_energy.py spechmmerCLine128.txt ./spec_results/spechmmerCLine128/stats.txt 
python ./Scripts/print_energy.py spechmmerCLine256.txt ./spec_results/spechmmerCLine256/stats.txt 
python ./Scripts/print_energy.py spechmmer16_32.txt ./spec_results/spechmmer16_32/stats.txt  
python ./Scripts/print_energy.py spechmmer32_64.txt ./spec_results/spechmmer32_64/stats.txt 
python ./Scripts/print_energy.py spechmmer64_128.txt ./spec_results/spechmmer64_128/stats.txt 
python ./Scripts/print_energy.py spechmmer128_256.txt ./spec_results/spechmmer128_256/stats.txt  
python ./Scripts/print_energy.py spechmmer256.txt ./spec_results/spechmmer256/stats.txt 
python ./Scripts/print_energy.py spechmmer512.txt ./spec_results/spechmmer512/stats.txt 
python ./Scripts/print_energy.py spechmmer1024.txt ./spec_results/spechmmer1024/stats.txt 
python ./Scripts/print_energy.py spechmmer2048.txt ./spec_results/spechmmer2048/stats.txt 
python ./Scripts/print_energy.py spechmmer4096.txt ./spec_results/spechmmer4096/stats.txt  
python ./Scripts/print_energy.py spechmmer32_64_512.txt ./spec_results/spechmmer32_64_512/stats.txt 
python ./Scripts/print_energy.py spechmmer64_128_1024.txt ./spec_results/spechmmer64_128_1024/stats.txt 
python ./Scripts/print_energy.py spechmmer128_256_2048.txt ./spec_results/spechmmer128_256_2048/stats.txt 

python ./Scripts/print_energy.py speclibm.txt ./spec_results/speclibm/stats.txt 
python ./Scripts/print_energy.py speclibmB.txt ./spec_results/speclibmB/stats.txt 
python ./Scripts/print_energy.py speclibmassoc1.txt ./spec_results/speclibmassoc1/stats.txt 
python ./Scripts/print_energy.py speclibmassoc2.txt ./spec_results/speclibmassoc2/stats.txt 
python ./Scripts/print_energy.py speclibmassoc4.txt ./spec_results/speclibmassoc4/stats.txt 
python ./Scripts/print_energy.py speclibmassoc8.txt ./spec_results/speclibmassoc8/stats.txt 
python ./Scripts/print_energy.py speclibmassoc16.txt ./spec_results/speclibmassoc16/stats.txt 
python ./Scripts/print_energy.py speclibmCLine16.txt ./spec_results/speclibmCLine16/stats.txt 
python ./Scripts/print_energy.py speclibmCLine32.txt ./spec_results/speclibmCLine32/stats.txt 
python ./Scripts/print_energy.py speclibmCLine64.txt ./spec_results/speclibmCLine64/stats.txt 
python ./Scripts/print_energy.py speclibmCLine128.txt ./spec_results/speclibmCLine128/stats.txt 
python ./Scripts/print_energy.py speclibmCLine256.txt ./spec_results/speclibmCLine256/stats.txt  
python ./Scripts/print_energy.py speclibm16_32.txt ./spec_results/speclibm16_32/stats.txt   
python ./Scripts/print_energy.py speclibm32_64.txt ./spec_results/speclibm32_64/stats.txt 
python ./Scripts/print_energy.py speclibm64_128.txt ./spec_results/speclibm64_128/stats.txt 
python ./Scripts/print_energy.py speclibm128_256.txt ./spec_results/speclibm128_256/stats.txt 
python ./Scripts/print_energy.py speclibm256.txt ./spec_results/speclibm256/stats.txt 
python ./Scripts/print_energy.py speclibm512.txt ./spec_results/speclibm512/stats.txt 
python ./Scripts/print_energy.py speclibm1024.txt ./spec_results/speclibm1024/stats.txt 
python ./Scripts/print_energy.py speclibm2048.txt ./spec_results/speclibm2048/stats.txt 
python ./Scripts/print_energy.py speclibm4096.txt ./spec_results/speclibm4096/stats.txt 
python ./Scripts/print_energy.py speclibm32_64_512.txt ./spec_results/speclibm32_64_512/stats.txt 
python ./Scripts/print_energy.py speclibm64_128_1024.txt ./spec_results/speclibm64_128_1024/stats.txt 
python ./Scripts/print_energy.py speclibm128_256_2048.txt ./spec_results/speclibm128_256_2048/stats.txt 


python ./Scripts/print_energy.py specmcf.txt ./spec_results/specmcf/stats.txt 
python ./Scripts/print_energy.py specmcfB.txt ./spec_results/specmcfB/stats.txt 
python ./Scripts/print_energy.py specmcfassoc1.txt ./spec_results/specmcfassoc1/stats.txt 
python ./Scripts/print_energy.py specmcfassoc2.txt ./spec_results/specmcfassoc2/stats.txt 
python ./Scripts/print_energy.py specmcfassoc4.txt ./spec_results/specmcfassoc4/stats.txt 
python ./Scripts/print_energy.py specmcfassoc8.txt ./spec_results/specmcfassoc8/stats.txt 
python ./Scripts/print_energy.py specmcfassoc16.txt ./spec_results/specmcfassoc16/stats.txt 
python ./Scripts/print_energy.py specmcfCLine16.txt ./spec_results/specmcfCLine16/stats.txt 
python ./Scripts/print_energy.py specmcfCLine32.txt ./spec_results/specmcfCLine32/stats.txt 
python ./Scripts/print_energy.py specmcfCLine64.txt ./spec_results/specmcfCLine64/stats.txt 
python ./Scripts/print_energy.py specmcfCLine128.txt ./spec_results/specmcfCLine128/stats.txt 
python ./Scripts/print_energy.py specmcfCLine256.txt ./spec_results/specmcfCLine256/stats.txt 
python ./Scripts/print_energy.py specmcf16_32.txt ./spec_results/specmcf16_32/stats.txt 
python ./Scripts/print_energy.py specmcf32_64.txt ./spec_results/specmcf32_64/stats.txt 
python ./Scripts/print_energy.py specmcf64_128.txt ./spec_results/specmcf64_128/stats.txt 
python ./Scripts/print_energy.py specmcf128_256.txt ./spec_results/specmcf128_256/stats.txt 
python ./Scripts/print_energy.py specmcf256.txt ./spec_results/specmcf256/stats.txt 
python ./Scripts/print_energy.py specmcf512.txt ./spec_results/specmcf512/stats.txt  
python ./Scripts/print_energy.py specmcf1024.txt ./spec_results/specmcf1024/stats.txt 
python ./Scripts/print_energy.py specmcf2048.txt ./spec_results/specmcf2048/stats.txt 
python ./Scripts/print_energy.py specmcf4096.txt ./spec_results/specmcf4096/stats.txt 
python ./Scripts/print_energy.py specmcf32_64_512.txt ./spec_results/specmcf32_64_512/stats.txt 
python ./Scripts/print_energy.py specmcf64_128_1024.txt ./spec_results/specmcf64_128_1024/stats.txt 
python ./Scripts/print_energy.py specmcf128_256_2048.txt ./spec_results/specmcf128_256_2048/stats.txt 

python ./Scripts/print_energy.py specsjeng.txt ./spec_results/specsjeng/stats.txt 
python ./Scripts/print_energy.py specsjengB.txt ./spec_results/specsjengB/stats.txt 
python ./Scripts/print_energy.py specsjengassoc1.txt ./spec_results/specsjengassoc1/stats.txt 
python ./Scripts/print_energy.py specsjengassoc2.txt ./spec_results/specsjengassoc2/stats.txt 
python ./Scripts/print_energy.py specsjengassoc4.txt ./spec_results/specsjengassoc4/stats.txt 
python ./Scripts/print_energy.py specsjengassoc8.txt ./spec_results/specsjengassoc8/stats.txt 
python ./Scripts/print_energy.py specsjengassoc16.txt ./spec_results/specsjengassoc16/stats.txt 
python ./Scripts/print_energy.py specsjengCLine16.txt ./spec_results/specsjengCLine16/stats.txt 
python ./Scripts/print_energy.py specsjengCLine32.txt ./spec_results/specsjengCLine32/stats.txt  
python ./Scripts/print_energy.py specsjengCLine64.txt ./spec_results/specsjengCLine64/stats.txt 
python ./Scripts/print_energy.py specsjengCLine128.txt ./spec_results/specsjengCLine128/stats.txt 
python ./Scripts/print_energy.py specsjengCLine256.txt ./spec_results/specsjengCLine256/stats.txt 
python ./Scripts/print_energy.py specsjeng16_32.txt ./spec_results/specsjeng16_32/stats.txt  
python ./Scripts/print_energy.py specsjeng32_64.txt ./spec_results/specsjeng32_64/stats.txt 
python ./Scripts/print_energy.py specsjeng64_128.txt ./spec_results/specsjeng64_128/stats.txt 
python ./Scripts/print_energy.py specsjeng128_256.txt ./spec_results/specsjeng128_256/stats.txt 
python ./Scripts/print_energy.py specsjeng256.txt ./spec_results/specsjeng256/stats.txt 
python ./Scripts/print_energy.py specsjeng512.txt ./spec_results/specsjeng512/stats.txt 
python ./Scripts/print_energy.py specsjeng1024.txt ./spec_results/specsjeng1024/stats.txt 
python ./Scripts/print_energy.py specsjeng2048.txt ./spec_results/specsjeng2048/stats.txt  
python ./Scripts/print_energy.py specsjeng4096.txt ./spec_results/specsjeng4096/stats.txt 
python ./Scripts/print_energy.py specsjeng32_64_512.txt ./spec_results/specsjeng32_64_512/stats.txt 
python ./Scripts/print_energy.py specsjeng64_128_1024.txt ./spec_results/specsjeng64_128_1024/stats.txt 
python ./Scripts/print_energy.py specsjeng128_256_2048.txt ./spec_results/specsjeng128_256_2048/stats.txt 
