#!/bin/bash

python ./Scripts/print_energy.py ./spec_results/specbzip/stats.txt specbzip.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipB/stats.txt specbzipB.txt
python ./Scripts/print_energy.py ./spec_results/specbzipassoc1/stats.txt specbzipassoc1.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipassoc2/stats.txt specbzipassoc2.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipassoc4/stats.txt specbzipassoc4.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipassoc8/stats.txt specbzipassoc8.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipassoc16/stats.txt specbzipassoc16.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipCLine16/stats.txt specbzipCLine16.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipCLine32/stats.txt specbzipCLine32.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipCLine64/stats.txt specbzipCLine64.txt 
python ./Scripts/print_energy.py ./spec_results/specbzipCLine128/stats.txt specbzipCLine128.txt  
python ./Scripts/print_energy.py ./spec_results/specbzipCLine256/stats.txt specbzipCLine256.txt  
python ./Scripts/print_energy.py ./spec_results/specbzip16_32/stats.txt specbzip16_32.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip32_64/stats.txt specbzip32_64.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip64_128/stats.txt specbzip64_128.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip128_256/stats.txt specbzip.128_256txt 
python ./Scripts/print_energy.py ./spec_results/specbzip256/stats.txt specbzip256.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip512/stats.txt specbzip512.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip1024/stats.txt specbzip1024.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip2048/stats.txt specbzip2048.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip4096/stats.txt specbzip4096.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip32_64_512/stats.txt specbzip32_64_512.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip64_128_1024/stats.txt specbzip64_128_1024.txt 
python ./Scripts/print_energy.py ./spec_results/specbzip128_256_2048/stats.txt specbzip128_256_2048.txt  

python ./Scripts/print_energy.py ./spec_results/spechmmer/stats.txt spechmmer.txt
python ./Scripts/print_energy.py ./spec_results/spechmmerB/stats.txt spechmmerB.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmerassoc1/stats.txt spechmmerassoc1.txt
python ./Scripts/print_energy.py ./spec_results/spechmmerassoc2/stats.txt spechmmerassoc2.txt
python ./Scripts/print_energy.py ./spec_results/spechmmerassoc4/stats.txt spechmmerassoc4.txt
python ./Scripts/print_energy.py ./spec_results/spechmmerassoc8/stats.txt spechmmerassoc8.txt
python ./Scripts/print_energy.py ./spec_results/spechmmerassoc16/stats.txt spechmmerassoc16.txt  
python ./Scripts/print_energy.py ./spec_results/spechmmerCLine16/stats.txt spechmmerCLine16.txt  
python ./Scripts/print_energy.py ./spec_results/spechmmerCLine32/stats.txt spechmmerCLine32.txt  
python ./Scripts/print_energy.py ./spec_results/spechmmerCLine64/stats.txt spechmmerCLine64.txt  
python ./Scripts/print_energy.py ./spec_results/spechmmerCLine128/stats.txt spechmmerCLine128.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmerCLine256/stats.txt spechmmerCLine256.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer16_32/stats.txt spechmmer16_32.txt  
python ./Scripts/print_energy.py ./spec_results/spechmmer32_64/stats.txt spechmmer32_64.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer64_128/stats.txt spechmmer64_128.txt
python ./Scripts/print_energy.py ./spec_results/spechmmer128_256/stats.txt spechmmer128_256.txt  
python ./Scripts/print_energy.py ./spec_results/spechmmer256/stats.txt spechmmer256.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer512/stats.txt spechmmer512.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer1024/stats.txt spechmmer1024.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer2048/stats.txt spechmmer2048.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer4096/stats.txt spechmmer4096.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer32_64_512/stats.txt spechmmer32_64_512.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer64_128_1024/stats.txt spechmmer64_128_1024.txt 
python ./Scripts/print_energy.py ./spec_results/spechmmer128_256_2048/stats.txt spechmmer128_256_2048.txt 

python ./Scripts/print_energy.py ./spec_results/speclibm/stats.txt speclibm.txt 
python ./Scripts/print_energy.py ./spec_results/speclibmB/stats.txt speclibmB.txt
python ./Scripts/print_energy.py ./spec_results/speclibmassoc1/stats.txt speclibmassoc1.txt 
python ./Scripts/print_energy.py ./spec_results/speclibmassoc2/stats.txt speclibmassoc2.txt 
python ./Scripts/print_energy.py ./spec_results/speclibmassoc4/stats.txt speclibmassoc4.txt 
python ./Scripts/print_energy.py ./spec_results/speclibmassoc8/stats.txt speclibmassoc8.txt 
python ./Scripts/print_energy.py ./spec_results/speclibmassoc16/stats.txt speclibmassoc16.txt
python ./Scripts/print_energy.py ./spec_results/speclibmCLine16/stats.txt speclibmCLine16.txt
python ./Scripts/print_energy.py ./spec_results/speclibmCLine32/stats.txt speclibmCLine32.txt
python ./Scripts/print_energy.py ./spec_results/speclibmCLine64/stats.txt speclibmCLine64.txt
python ./Scripts/print_energy.py ./spec_results/speclibmCLine128/stats.txt speclibmCLine128.txt  
python ./Scripts/print_energy.py ./spec_results/speclibmCLine256/stats.txt speclibmCLine256.txt  
python ./Scripts/print_energy.py ./spec_results/speclibm16_32/stats.txt speclibm16_32.txt  
python ./Scripts/print_energy.py ./spec_results/speclibm32_64/stats.txt speclibm32_64.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm64_128/stats.txt speclibm64_128.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm128_256/stats.txt speclibm128_256.txt
python ./Scripts/print_energy.py ./spec_results/speclibm256/stats.txt speclibm256.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm512/stats.txt speclibm512.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm1024/stats.txt speclibm1024.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm2048/stats.txt speclibm2048.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm4096/stats.txt speclibm4096.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm32_64_512/stats.txt speclibm32_64_512.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm64_128_1024/stats.txt speclibm64_128_1024.txt 
python ./Scripts/print_energy.py ./spec_results/speclibm128_256_2048/stats.txt speclibm128_256_2048.txt 


python ./Scripts/print_energy.py ./spec_results/specmcf/stats.txt specmcf.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfB/stats.txt specmcfB.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfassoc1/stats.txt specmcfassoc1.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfassoc2/stats.txt specmcfassoc2.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfassoc4/stats.txt specmcfassoc4.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfassoc8/stats.txt specmcfassoc8.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfassoc16/stats.txt specmcfassoc16.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfCLine16/stats.txt specmcfCLine16.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfCLine32/stats.txt specmcfCLine32.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfCLine64/stats.txt specmcfCLine64.txt 
python ./Scripts/print_energy.py ./spec_results/specmcfCLine128/stats.txt specmcfCLine128.txt
python ./Scripts/print_energy.py ./spec_results/specmcfCLine256/stats.txt specmcfCLine256.txt
python ./Scripts/print_energy.py ./spec_results/specmcf16_32/stats.txt specmcf16_32.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf32_64/stats.txt specmcf32_64.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf64_128/stats.txt specmcf64_128.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf128_256/stats.txt specmcf128_256.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf256/stats.txt specmcf256.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf512/stats.txt specmcf512.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf1024/stats.txt specmcf1024.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf2048/stats.txt specmcf2048.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf4096/stats.txt specmcf4096.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf32_64_512/stats.txt specmcf32_64_512.txt  
python ./Scripts/print_energy.py ./spec_results/specmcf64_128_1024/stats.txt specmcf64_128_1024.txt 
python ./Scripts/print_energy.py ./spec_results/specmcf128_256_2048/stats.txt specmcf128_256_2048.txt 

python ./Scripts/print_energy.py ./spec_results/specsjeng/stats.txt specsjeng.txt
python ./Scripts/print_energy.py ./spec_results/specsjengB/stats.txt specsjengB.txt 
python ./Scripts/print_energy.py ./spec_results/specsjengassoc1/stats.txt specsjengassoc1.txt
python ./Scripts/print_energy.py ./spec_results/specsjengassoc2/stats.txt specsjengassoc2.txt
python ./Scripts/print_energy.py ./spec_results/specsjengassoc4/stats.txt specsjengassoc4.txt
python ./Scripts/print_energy.py ./spec_results/specsjengassoc8/stats.txt specsjengassoc8.txt
python ./Scripts/print_energy.py ./spec_results/specsjengassoc16/stats.txt specsjengassoc16.txt  
python ./Scripts/print_energy.py ./spec_results/specsjengCLine16/stats.txt specsjengCLine16.txt  
python ./Scripts/print_energy.py ./spec_results/specsjengCLine32/stats.txt specsjengCLine32.txt  
python ./Scripts/print_energy.py ./spec_results/specsjengCLine64/stats.txt specsjengCLine64.txt  
python ./Scripts/print_energy.py ./spec_results/specsjengCLine128/stats.txt specsjengCLine128.txt 
python ./Scripts/print_energy.py ./spec_results/specsjengCLine256/stats.txt specsjengCLine256.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng16_32/stats.txt specsjeng16_32.txt  
python ./Scripts/print_energy.py ./spec_results/specsjeng32_64/stats.txt specsjeng32_64.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng64_128/stats.txt specsjeng64_128.txt
python ./Scripts/print_energy.py ./spec_results/specsjeng128_256/stats.txt specsjeng128_256.txt  
python ./Scripts/print_energy.py ./spec_results/specsjeng256/stats.txt specsjeng256.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng512/stats.txt specsjeng512.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng1024/stats.txt specsjeng1024.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng2048/stats.txt specsjeng2048.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng4096/stats.txt specsjeng4096.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng32_64_512/stats.txt specsjeng32_64_512.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng64_128_1024/stats.txt specsjeng64_128_1024.txt 
python ./Scripts/print_energy.py ./spec_results/specsjeng128_256_2048/stats.txt specsjeng128_256_2048.txt 
